### ISSUE TITLE
managedResourceGroup conflicts when redeploying

### ISSUE THREAD

**Issue by cleverkm** [nginxinc/nginxaas-for-azure-snippets#17]
When defining a managedResourceGroup in the Bicep template it runs fine the first time, but the second it complains about it already exists.

Error message from deployment:
```
{"code":"DeploymentFailed","target":"/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Resources/deployments/XXX","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"The managed resource group name XXX conflicts with an existing resource group name."}]}
```

Bicep code:
```
resource deployment 'Nginx.NginxPlus/nginxDeployments@2022-08-01' = {
  name: nginxDeploymentName
  location: location
  sku: {
    name: sku
  }
  identity:  {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${userAssignedIdentity.id}': {}
    }
  }
  properties: {
    enableDiagnosticsSupport: false
    networkProfile: {
      frontEndIPConfiguration: {
        publicIPAddresses: [
          {
            id: publicIpId
          }
        ]
        privateIPAddresses: []
      }
      networkInterfaceConfiguration: {
        subnetId: subnetId
      }
    }
    managedResourceGroup: managedResourceGroupName
  }
}
```

**Comment by agazeley** [comment]
Thank you for reporting this issue. We have created an internal ticket and will be working on a resolution to this bug.

**Comment by techarch** [comment]
I am also experiencing the issue - for example when changing the paths for the Nginx.NginxPlus/nginxDeployments/certificates resource. I have to delete the ngix resource and redeploy the Bicep templates to work around it.

**Comment by agazeley** [comment]
> I am also experiencing the issue - for example when changing the paths for the Nginx.NginxPlus/nginxDeployments/certificates resource. I have to delete the ngix resource and redeploy the Bicep templates to work around it.

Hi @techarch  can you describe your problem a bit more? Is it changing the certificates virtual paths or the actual path of the resource (the resource name or resource group/subscription)? 

As of now moving resources across resource groups or re-naming is not supported and will result in a newly created resource.

**Comment by agazeley** [comment]
Hi @cleverkm 

The upstream issue has been fixed. You should be able to update your deployment with a specified managed resource group (assuming you are not modifying that value).
