### ISSUE TITLE
What is the Azure ip range used to access the storage account?

### ISSUE THREAD

**Issue by techarch** [nginxinc/nginxaas-for-azure-snippets#22]
I am finding that for the logs to be written to the storage account (when inside a vnet) I have to open the traffic up.
I checked the MS Azure Service tags and IP ranges but could not locate anything for nginx for Azure.
Could you share what range of ip addresses I should include the storage account firewall rules?

**Comment by UnwashedMeme** [comment]
We don't currently have a ServiceTag or a established outbound IP list. There are some changes coming up (soon) to work more natively with Azure Monitor for sending to a Log Analytics workspace and Storage Accounts that should make this easier.

When it lands we'll post on https://docs.nginx.com/nginxaas/azure/changelog/; I will try to see that this ticket gets updated too.

**Comment by techarch** [comment]
@UnwashedMeme Are there any updates on this topic. I have been looking at the changelog on a regular basis but have not seen anything new.

**Comment by UnwashedMeme** [comment]
@techarch Azure Monitor logs is in its final stage of testing before general release.

**Comment by UnwashedMeme** [comment]
@techarch Docs are updated https://docs.nginx.com/nginxaas/azure/monitoring/azure-integrated-nginx-logs/
