### ISSUE TITLE
How to configure the NCU using Bicep?

### ISSUE THREAD

**Issue by techarch** [nginxinc/nginxaas-for-azure-snippets#26]
The October 11, 2023 post in the [change log](https://docs.nginx.com/nginxaas/azure/changelog/) indicates that "_NGINXaaS for Azure now supports smaller deployments. You can now create or scale deployments to a capacity of 10 NCUs, ideal for small workloads._".
The Bicep definition only includes the sku property with the value 'standard_Monthly'.
How can we reduce or specify the NCU using Bicep? Will a new property be created (e.g.: ncu), or is there a new value for the sku reflecting the 10 NCU value?

**Comment by agazeley** [comment]
Hi @techarch,

There is a PR out [here](https://github.com/nginxinc/nginxaas-for-azure-snippets/pull/27) to add the examples for scaling utilizing the new `scalingProperties` and `capacity` for the `2023-04-01` api-version. Please let us know if you encounter any issues with these snippets!

**Comment by techarch** [comment]
Thank you @agazeley, I was able to use the new properties and adjust the NCU capacity. 👍

**Comment by UnwashedMeme** [comment]
Closing as it looks like this is done. Please reopen if there are any remaining issues.
